#!/bin/bash

# Print the current Juju model if available.
_curmodel() {
    current=`juju switch 2> /dev/null`
    if [ $? -ne 0 ]; then
        echo '<no controller>'
        return
    fi
    if [[ $current == *":"* ]]; then
        echo $current | cut -d ':' -f 2
        return
    fi
    echo '<no model selected>'
}

# Set up the prompt.
export PS1="\[\033[01;32m\]\$(_curmodel)\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

# Start the SSH agent and add the jujushell key if it exists.
eval `ssh-agent -s` > /dev/null
for key in ~/.ssh/id_*; do
    [ -f "$key" ] || continue
    if grep -q PRIVATE "$key"; then
        ssh-add "$key" 2> /dev/null
    fi
done
