#!/bin/bash
mkdir -p ~/.kube
k8smaster=$(juju status --format=json | jq '.applications["kubernetes-master"].units | keys[0]' -r)
juju scp $k8smaster:~/config ~/.kube/config

cloud=$(juju status --format=json | jq '.model.cloud' -r)

if [ $cloud = "aws" ]; then
    aws_setup
fi

function aws_setup {
    juju deploy cs:~containers/aws-integrator
}
