#!/usr/bin/env python3

"""The terminal service."""

from tornado import ioloop
from tornado.options import define, options

from ts import app


def main():
    define('port', default=8765, help='the port to use for the server')
    define('command', default='bash', help='the command to expose')
    options.parse_command_line()
    close = app.start(options.port, options.command)
    loop = ioloop.IOLoop.instance()
    try:
        loop.start()
    except KeyboardInterrupt:
        print('quitting')
    finally:
        close()
        loop.close()


if __name__ == '__main__':
    main()
